version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
      - rm -rf lib/numpy lib/numpy* lib/__pycache__/numpy*

  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip lambda_cicd.py
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp deployment_package.zip s3://github-lambda-cicd-b1/
      - echo "Updating Lambda function via S3..."
      - aws lambda update-function-code --function-name github-lambda-cicd --s3-bucket github-lambda-cicd-b1 --s3-key deployment_package.zip
      - echo "Deployment complete!"